2024-02-09 20:54:23,585 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Fri, 09 Feb 2024 20:54:23 +0000. Up 8.17 seconds.
2024-02-09 20:54:23,586 - main.py[DEBUG]: No kernel command line url found.
2024-02-09 20:54:23,586 - main.py[DEBUG]: Closing stdin.
2024-02-09 20:54:23,587 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2024-02-09 20:54:23,588 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-02-09 20:54:23,605 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2024-02-09 20:54:23,606 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-02-09 20:54:23,620 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2024-02-09 20:54:23,621 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-02-09 20:54:23,627 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2024-02-09 20:54:23,628 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-02-09 20:54:23,646 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2024-02-09 20:54:23,647 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-02-09 20:54:23,668 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2024-02-09 20:54:23,679 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-02-09 20:54:23,704 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2024-02-09 20:54:23,705 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-02-09 20:54:23,732 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2024-02-09 20:54:23,733 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-02-09 20:54:23,762 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2024-02-09 20:54:23,763 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-02-09 20:54:23,793 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2024-02-09 20:54:23,794 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2024-02-09 20:54:23,794 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2024-02-09 20:54:23,795 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2024-02-09 20:54:23,796 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2024-02-09 20:54:23,798 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-02-09 20:54:23,799 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-02-09 20:54:23,800 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2024-02-09 20:54:23,800 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2024-02-09 20:54:23,801 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-02-09 20:54:23,802 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-02-09 20:54:23,803 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2024-02-09 20:54:23,821 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2024-02-09 20:54:23,830 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2024-02-09 20:54:23,846 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2024-02-09 20:54:23,872 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2024-02-09 20:54:23,878 - stages.py[DEBUG]: no cache found
2024-02-09 20:54:23,892 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2024-02-09 20:54:23,895 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-02-09 20:54:23,912 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-02-09 20:54:23,912 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2024-02-09 20:54:23,928 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2024-02-09 20:54:23,928 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2024-02-09 20:54:23,928 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2024-02-09 20:54:23,928 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2024-02-09 20:54:23,929 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2024-02-09 20:54:23,929 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2024-02-09 20:54:23,929 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2024-02-09 20:54:23,929 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2024-02-09 20:54:23,929 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2024-02-09 20:54:23,929 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2024-02-09 20:54:23,930 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2024-02-09 20:54:23,930 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2024-02-09 20:54:23,930 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2024-02-09 20:54:23,930 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2024-02-09 20:54:23,930 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2024-02-09 20:54:23,930 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-02-09 20:54:23,940 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2024-02-09 20:54:23,941 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2024-02-09 20:54:23,941 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:23,950 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2024-02-09 20:54:23,950 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2024-02-09 20:54:23,950 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:23,967 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2435b) after 1 attempts
2024-02-09 20:54:23,968 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:23,982 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 305b) after 1 attempts
2024-02-09 20:54:23,982 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:23,985 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2024-02-09 20:54:23,985 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:23,990 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2024-02-09 20:54:23,990 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:23,993 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2024-02-09 20:54:23,993 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,000 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2024-02-09 20:54:24,000 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,003 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2024-02-09 20:54:24,003 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,005 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2024-02-09 20:54:24,006 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,011 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2024-02-09 20:54:24,012 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,014 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2024-02-09 20:54:24,015 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,018 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 198b) after 1 attempts
2024-02-09 20:54:24,018 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,030 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2024-02-09 20:54:24,030 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,033 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2024-02-09 20:54:24,033 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,036 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2024-02-09 20:54:24,036 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,041 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2024-02-09 20:54:24,041 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,050 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2024-02-09 20:54:24,050 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,056 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2024-02-09 20:54:24,057 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,070 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2024-02-09 20:54:24,070 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,073 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2024-02-09 20:54:24,073 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,076 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/ (200, 230b) after 1 attempts
2024-02-09 20:54:24,076 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,080 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/ipv4-associations/ (200, 13b) after 1 attempts
2024-02-09 20:54:24,080 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/ipv4-associations/3.133.101.230' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/ipv4-associations/3.133.101.230', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,090 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/ipv4-associations/3.133.101.230 (200, 13b) after 1 attempts
2024-02-09 20:54:24,090 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,093 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/device-number (200, 1b) after 1 attempts
2024-02-09 20:54:24,093 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,100 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/interface-id (200, 21b) after 1 attempts
2024-02-09 20:54:24,101 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,110 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/local-hostname (200, 43b) after 1 attempts
2024-02-09 20:54:24,111 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,120 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/local-ipv4s (200, 13b) after 1 attempts
2024-02-09 20:54:24,120 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,130 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/mac (200, 17b) after 1 attempts
2024-02-09 20:54:24,130 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,133 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/owner-id (200, 12b) after 1 attempts
2024-02-09 20:54:24,133 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,140 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/public-hostname (200, 49b) after 1 attempts
2024-02-09 20:54:24,140 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,143 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/public-ipv4s (200, 13b) after 1 attempts
2024-02-09 20:54:24,143 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,150 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/security-group-ids (200, 41b) after 1 attempts
2024-02-09 20:54:24,150 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,153 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/security-groups (200, 64b) after 1 attempts
2024-02-09 20:54:24,153 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,160 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/subnet-id (200, 24b) after 1 attempts
2024-02-09 20:54:24,160 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,163 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
2024-02-09 20:54:24,163 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,170 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/vpc-id (200, 21b) after 1 attempts
2024-02-09 20:54:24,170 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,173 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2024-02-09 20:54:24,173 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,180 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:61:47:4b:b8:df/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2024-02-09 20:54:24,180 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,183 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2024-02-09 20:54:24,183 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,190 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2024-02-09 20:54:24,190 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,193 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2024-02-09 20:54:24,193 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,195 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 9b) after 1 attempts
2024-02-09 20:54:24,195 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,200 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2024-02-09 20:54:24,200 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,202 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2024-02-09 20:54:24,202 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,210 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2024-02-09 20:54:24,210 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,215 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2024-02-09 20:54:24,215 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,220 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2024-02-09 20:54:24,220 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,230 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2024-02-09 20:54:24,230 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,240 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 43b) after 1 attempts
2024-02-09 20:54:24,240 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,250 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2024-02-09 20:54:24,250 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,253 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2024-02-09 20:54:24,253 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,260 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2024-02-09 20:54:24,260 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,263 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2024-02-09 20:54:24,263 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,270 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 43b) after 1 attempts
2024-02-09 20:54:24,270 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,272 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 13b) after 1 attempts
2024-02-09 20:54:24,273 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,280 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2024-02-09 20:54:24,280 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,282 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2024-02-09 20:54:24,282 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,285 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 49b) after 1 attempts
2024-02-09 20:54:24,285 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,290 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 13b) after 1 attempts
2024-02-09 20:54:24,290 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,293 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2024-02-09 20:54:24,293 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,297 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 64b) after 1 attempts
2024-02-09 20:54:24,297 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,310 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2024-02-09 20:54:24,310 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,313 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 477b) after 1 attempts
2024-02-09 20:54:24,314 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,320 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1167b) after 1 attempts
2024-02-09 20:54:24,320 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,323 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1487b) after 1 attempts
2024-02-09 20:54:24,324 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-02-09 20:54:24,326 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2024-02-09 20:54:24,326 - util.py[DEBUG]: Crawl of metadata service took 0.397 seconds
2024-02-09 20:54:24,330 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2024-02-09 20:54:24,331 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2024-02-09 20:54:24,332 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2024-02-09 20:54:24,332 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2024-02-09 20:54:24,333 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmp7xzmdso3) - w: [600] 12115 bytes/chars
2024-02-09 20:54:24,335 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpkfgth3_7) - w: [644] 7973 bytes/chars
2024-02-09 20:54:24,335 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2024-02-09 20:54:24,335 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2024-02-09 20:54:24,335 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-02-09 20:54:24,335 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-02-09 20:54:24,335 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,363 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-02-09 20:54:24,364 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-02-09 20:54:24,364 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,365 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-02-09 20:54:24,366 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-02-09 20:54:24,366 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,380 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-02-09 20:54:24,380 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-02-09 20:54:24,380 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,387 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-02-09 20:54:24,387 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-02-09 20:54:24,388 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,400 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-02-09 20:54:24,400 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,400 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-02-09 20:54:24,401 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-02-09 20:54:24,401 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-04a2fb82429909c7b'
2024-02-09 20:54:24,402 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b (recursive=True)
2024-02-09 20:54:24,408 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/handlers (recursive=False)
2024-02-09 20:54:24,425 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b (recursive=True)
2024-02-09 20:54:24,433 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/scripts (recursive=False)
2024-02-09 20:54:24,434 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b (recursive=True)
2024-02-09 20:54:24,453 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem (recursive=False)
2024-02-09 20:54:24,454 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-04a2fb82429909c7b/datasource (quiet=False)
2024-02-09 20:54:24,454 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/datasource - wb: [644] 29 bytes
2024-02-09 20:54:24,455 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/datasource (recursive=False)
2024-02-09 20:54:24,457 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/datasource (recursive=False)
2024-02-09 20:54:24,457 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2024-02-09 20:54:24,458 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2024-02-09 20:54:24,459 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2024-02-09 20:54:24,460 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2024-02-09 20:54:24,460 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2024-02-09 20:54:24,460 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2024-02-09 20:54:24,460 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2024-02-09 20:54:24,461 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2024-02-09 20:54:24,462 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2024-02-09 20:54:24,463 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2024-02-09 20:54:24,463 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2024-02-09 20:54:24,464 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2024-02-09 20:54:24,465 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2024-02-09 20:54:24,466 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2024-02-09 20:54:24,468 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12605 bytes
2024-02-09 20:54:24,479 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/obj.pkl (recursive=False)
2024-02-09 20:54:24,481 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/obj.pkl (recursive=False)
2024-02-09 20:54:24,482 - main.py[DEBUG]: [net] init will now be targeting instance id: i-04a2fb82429909c7b. new=True
2024-02-09 20:54:24,483 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-02-09 20:54:24,483 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-02-09 20:54:24,483 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,509 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-02-09 20:54:24,509 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-02-09 20:54:24,509 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,511 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-02-09 20:54:24,511 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-02-09 20:54:24,511 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,515 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-02-09 20:54:24,515 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-02-09 20:54:24,515 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,521 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-02-09 20:54:24,522 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-02-09 20:54:24,522 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,525 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-02-09 20:54:24,525 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,525 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-02-09 20:54:24,526 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-02-09 20:54:24,527 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-02-09 20:54:24,527 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-02-09 20:54:24,527 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-02-09 20:54:24,527 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2024-02-09 20:54:24,527 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/name_assign_type
2024-02-09 20:54:24,527 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-02-09 20:54:24,527 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-02-09 20:54:24,527 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2024-02-09 20:54:24,527 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/carrier
2024-02-09 20:54:24,528 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2024-02-09 20:54:24,528 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/addr_assign_type
2024-02-09 20:54:24,528 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2024-02-09 20:54:24,528 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens5/uevent
2024-02-09 20:54:24,528 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-02-09 20:54:24,528 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-02-09 20:54:24,528 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2024-02-09 20:54:24,528 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2024-02-09 20:54:24,528 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens5/device/device
2024-02-09 20:54:24,528 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2024-02-09 20:54:24,528 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2024-02-09 20:54:24,529 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2024-02-09 20:54:24,529 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2024-02-09 20:54:24,539 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-02-09 20:54:24,539 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-02-09 20:54:24,540 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2024-02-09 20:54:24,540 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2024-02-09 20:54:24,540 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/type
2024-02-09 20:54:24,540 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2024-02-09 20:54:24,540 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2024-02-09 20:54:24,540 - stages.py[DEBUG]: network config disabled by system_cfg
2024-02-09 20:54:24,540 - stages.py[INFO]: network config is disabled by system_cfg
2024-02-09 20:54:24,541 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2024-02-09 20:54:24,541 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2024-02-09 20:54:24,541 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/user-data.txt - wb: [600] 2435 bytes
2024-02-09 20:54:24,542 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/user-data.txt (recursive=False)
2024-02-09 20:54:24,543 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/user-data.txt (recursive=False)
2024-02-09 20:54:24,545 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,549 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/user-data.txt.i - wb: [600] 2457 bytes
2024-02-09 20:54:24,550 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/user-data.txt.i (recursive=False)
2024-02-09 20:54:24,551 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/user-data.txt.i (recursive=False)
2024-02-09 20:54:24,552 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/vendor-data.txt - wb: [600] 0 bytes
2024-02-09 20:54:24,553 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/vendor-data.txt (recursive=False)
2024-02-09 20:54:24,554 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/vendor-data.txt (recursive=False)
2024-02-09 20:54:24,556 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/vendor-data.txt.i - wb: [600] 308 bytes
2024-02-09 20:54:24,557 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/vendor-data.txt.i (recursive=False)
2024-02-09 20:54:24,558 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/vendor-data.txt.i (recursive=False)
2024-02-09 20:54:24,569 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/vendor-data2.txt - wb: [600] 0 bytes
2024-02-09 20:54:24,570 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/vendor-data2.txt (recursive=False)
2024-02-09 20:54:24,571 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/vendor-data2.txt (recursive=False)
2024-02-09 20:54:24,573 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/vendor-data2.txt.i - wb: [600] 308 bytes
2024-02-09 20:54:24,574 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/vendor-data2.txt.i (recursive=False)
2024-02-09 20:54:24,575 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/vendor-data2.txt.i (recursive=False)
2024-02-09 20:54:24,577 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-02-09 20:54:24,578 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-19-126.us-east-2.compute.internal (ip-172-31-19-126)
2024-02-09 20:54:24,578 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-19-126.us-east-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-02-09 20:54:24,775 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-19-126.us-east-2.compute.internal
2024-02-09 20:54:24,775 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-19-126.us-east-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-02-09 20:54:24,780 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmpa9v88wet) - w: [644] 92 bytes/chars
2024-02-09 20:54:24,781 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/consume_data - wb: [644] 25 bytes
2024-02-09 20:54:24,782 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/consume_data (recursive=False)
2024-02-09 20:54:24,784 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/consume_data (recursive=False)
2024-02-09 20:54:24,784 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/consume_data'>)
2024-02-09 20:54:24,785 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2024-02-09 20:54:24,785 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2024-02-09 20:54:24,786 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2024-02-09 20:54:24,786 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2024-02-09 20:54:24,786 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2024-02-09 20:54:24,786 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2024-02-09 20:54:24,786 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2024-02-09 20:54:24,787 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2024-02-09 20:54:24,787 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2024-02-09 20:54:24,788 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2024-02-09 20:54:24,788 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2024-02-09 20:54:24,788 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2024-02-09 20:54:24,788 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2024-02-09 20:54:24,788 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2024-02-09 20:54:24,788 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2024-02-09 20:54:24,788 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2024-02-09 20:54:24,788 - __init__.py[DEBUG]: {'Content-Type': 'text/cloud-config; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="cloud-config.txt"'}
2024-02-09 20:54:24,788 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
2024-02-09 20:54:24,789 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,790 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2024-02-09 20:54:24,791 - __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="user-data.txt"'}
2024-02-09 20:54:24,791 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
2024-02-09 20:54:24,791 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 1786 bytes
2024-02-09 20:54:24,792 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/scripts/user-data.txt (recursive=False)
2024-02-09 20:54:24,793 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/scripts/user-data.txt (recursive=False)
2024-02-09 20:54:24,794 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2024-02-09 20:54:24,795 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/cloud-config.txt - wb: [600] 154 bytes
2024-02-09 20:54:24,796 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/cloud-config.txt (recursive=False)
2024-02-09 20:54:24,797 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/cloud-config.txt (recursive=False)
2024-02-09 20:54:24,797 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2024-02-09 20:54:24,798 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2024-02-09 20:54:24,798 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2024-02-09 20:54:24,798 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2024-02-09 20:54:24,798 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2024-02-09 20:54:24,798 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2024-02-09 20:54:24,798 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2024-02-09 20:54:24,798 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2024-02-09 20:54:24,798 - stages.py[DEBUG]: no vendordata from datasource
2024-02-09 20:54:24,798 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2024-02-09 20:54:24,798 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2024-02-09 20:54:24,798 - stages.py[DEBUG]: no vendordata2 from datasource
2024-02-09 20:54:24,798 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2024-02-09 20:54:24,798 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-02-09 20:54:24,799 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-02-09 20:54:24,799 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,823 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-02-09 20:54:24,823 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-02-09 20:54:24,823 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,824 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-02-09 20:54:24,824 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-02-09 20:54:24,824 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,827 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-02-09 20:54:24,827 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-02-09 20:54:24,827 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,843 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-02-09 20:54:24,843 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-02-09 20:54:24,843 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,846 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-02-09 20:54:24,846 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,846 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-02-09 20:54:24,846 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2024-02-09 20:54:24,848 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2024-02-09 20:54:24,848 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:24,850 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:24,850 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:24,984 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2024-02-09 20:54:24,985 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2024-02-09 20:54:24,985 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2024-02-09 20:54:25,001 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2024-02-09 20:54:25,003 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 16739 bytes
2024-02-09 20:54:25,005 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/obj.pkl (recursive=False)
2024-02-09 20:54:25,007 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/obj.pkl (recursive=False)
2024-02-09 20:54:25,008 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2024-02-09 20:54:25,008 - main.py[DEBUG]: no di_report found in config.
2024-02-09 20:54:25,011 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,011 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,017 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,017 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,029 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,030 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,033 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,034 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,038 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,038 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,049 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,049 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,055 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,055 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,059 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,059 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,070 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,070 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,074 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,074 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,077 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,077 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,089 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,089 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,092 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,093 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,096 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,096 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,110 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,110 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,114 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:25,114 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:25,117 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-02-09 20:54:25,118 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2024-02-09 20:54:25,119 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2024-02-09 20:54:25,119 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f2cfdd08d60>)
2024-02-09 20:54:25,119 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2024-02-09 20:54:25,119 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2024-02-09 20:54:25,119 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2024-02-09 20:54:25,120 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2024-02-09 20:54:25,123 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_seed_random - wb: [644] 24 bytes
2024-02-09 20:54:25,124 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_seed_random (recursive=False)
2024-02-09 20:54:25,125 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_seed_random (recursive=False)
2024-02-09 20:54:25,126 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_seed_random'>)
2024-02-09 20:54:25,126 - cc_seed_random.py[DEBUG]: no command provided
2024-02-09 20:54:25,126 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2024-02-09 20:54:25,126 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2024-02-09 20:54:25,127 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2024-02-09 20:54:25,127 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f2cfdd08d60>)
2024-02-09 20:54:25,127 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2024-02-09 20:54:25,127 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2024-02-09 20:54:25,127 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2024-02-09 20:54:25,127 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2024-02-09 20:54:25,128 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_write_files - wb: [644] 25 bytes
2024-02-09 20:54:25,128 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_write_files (recursive=False)
2024-02-09 20:54:25,130 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_write_files (recursive=False)
2024-02-09 20:54:25,130 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_write_files'>)
2024-02-09 20:54:25,131 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2024-02-09 20:54:25,131 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2024-02-09 20:54:25,131 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2024-02-09 20:54:25,131 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2024-02-09 20:54:25,131 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_write_metadata - wb: [644] 25 bytes
2024-02-09 20:54:25,132 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_write_metadata (recursive=False)
2024-02-09 20:54:25,133 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_write_metadata (recursive=False)
2024-02-09 20:54:25,134 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_write_metadata'>)
2024-02-09 20:54:25,134 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 9 bytes
2024-02-09 20:54:25,153 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2024-02-09 20:54:25,154 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2024-02-09 20:54:25,155 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2024-02-09 20:54:25,155 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2024-02-09 20:54:25,156 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2024-02-09 20:54:25,156 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2024-02-09 20:54:25,158 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2024-02-09 20:54:25,158 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2024-02-09 20:54:25,158 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2024-02-09 20:54:25,158 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2024-02-09 20:54:25,158 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f2cfdd08f70>)
2024-02-09 20:54:25,158 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2024-02-09 20:54:25,158 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2024-02-09 20:54:25,192 - util.py[DEBUG]: Reading from /proc/1449/mountinfo (quiet=False)
2024-02-09 20:54:25,193 - util.py[DEBUG]: Read 2926 bytes from /proc/1449/mountinfo
2024-02-09 20:54:25,193 - util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
2024-02-09 20:54:25,193 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
2024-02-09 20:54:25,193 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
2024-02-09 20:54:25,194 - util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
2024-02-09 20:54:25,194 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
2024-02-09 20:54:25,321 - util.py[DEBUG]: resize_devices took 0.129 seconds
2024-02-09 20:54:25,322 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
2024-02-09 20:54:25,322 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2024-02-09 20:54:25,322 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2024-02-09 20:54:25,323 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2024-02-09 20:54:25,323 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f2cfdd08d60>)
2024-02-09 20:54:25,323 - util.py[DEBUG]: Reading from /proc/1449/mountinfo (quiet=False)
2024-02-09 20:54:25,323 - util.py[DEBUG]: Read 2926 bytes from /proc/1449/mountinfo
2024-02-09 20:54:25,324 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
2024-02-09 20:54:25,324 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2024-02-09 20:54:25,325 - util.py[DEBUG]: Forked child 1582 who will run callback log_time
2024-02-09 20:54:25,326 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2024-02-09 20:54:25,326 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2024-02-09 20:54:25,326 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2024-02-09 20:54:25,326 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2024-02-09 20:54:25,328 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2024-02-09 20:54:25,328 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_disk_setup - wb: [644] 25 bytes
2024-02-09 20:54:25,340 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_disk_setup (recursive=False)
2024-02-09 20:54:25,343 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_disk_setup (recursive=False)
2024-02-09 20:54:25,344 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_disk_setup'>)
2024-02-09 20:54:25,344 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2024-02-09 20:54:25,344 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2024-02-09 20:54:25,345 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2024-02-09 20:54:25,345 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_mounts - wb: [644] 23 bytes
2024-02-09 20:54:25,346 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_mounts (recursive=False)
2024-02-09 20:54:25,369 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_mounts (recursive=False)
2024-02-09 20:54:25,371 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_mounts'>)
2024-02-09 20:54:25,372 - cc_mounts.py[DEBUG]: mounts configuration is []
2024-02-09 20:54:25,372 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2024-02-09 20:54:25,372 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2024-02-09 20:54:25,372 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2024-02-09 20:54:25,372 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2024-02-09 20:54:25,372 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2024-02-09 20:54:25,372 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2024-02-09 20:54:25,373 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2024-02-09 20:54:25,373 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2024-02-09 20:54:25,373 - cc_mounts.py[DEBUG]: changed default device swap => None
2024-02-09 20:54:25,373 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2024-02-09 20:54:25,373 - cc_mounts.py[DEBUG]: no need to setup swap
2024-02-09 20:54:25,373 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2024-02-09 20:54:25,373 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2024-02-09 20:54:25,373 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2024-02-09 20:54:25,373 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2024-02-09 20:54:25,373 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f2cfdd0d9d0>)
2024-02-09 20:54:25,374 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2024-02-09 20:54:25,374 - util.py[DEBUG]: Read 92 bytes from /var/lib/cloud/data/set-hostname
2024-02-09 20:54:25,374 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2024-02-09 20:54:25,374 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2024-02-09 20:54:25,374 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2024-02-09 20:54:25,374 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2024-02-09 20:54:25,374 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f2cfdd08d60>)
2024-02-09 20:54:25,374 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-19-126.us-east-2.compute.internal (ip-172-31-19-126)
2024-02-09 20:54:25,375 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2024-02-09 20:54:25,388 - util.py[DEBUG]: backgrounded Resizing took 0.062 seconds
2024-02-09 20:54:25,389 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-19-126.us-east-2.compute.internal in 1 files
2024-02-09 20:54:25,390 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 43 bytes
2024-02-09 20:54:25,391 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2024-02-09 20:54:25,394 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2024-02-09 20:54:25,395 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2024-02-09 20:54:25,395 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2024-02-09 20:54:25,396 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2024-02-09 20:54:25,396 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f2cfdd08bb0>)
2024-02-09 20:54:25,396 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2024-02-09 20:54:25,396 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2024-02-09 20:54:25,396 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2024-02-09 20:54:25,396 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2024-02-09 20:54:25,397 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_ca_certs - wb: [644] 25 bytes
2024-02-09 20:54:25,397 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_ca_certs (recursive=False)
2024-02-09 20:54:25,399 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_ca_certs (recursive=False)
2024-02-09 20:54:25,410 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_ca_certs'>)
2024-02-09 20:54:25,410 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2024-02-09 20:54:25,410 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2024-02-09 20:54:25,410 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2024-02-09 20:54:25,410 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2024-02-09 20:54:25,411 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_rsyslog - wb: [644] 25 bytes
2024-02-09 20:54:25,412 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_rsyslog (recursive=False)
2024-02-09 20:54:25,414 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_rsyslog (recursive=False)
2024-02-09 20:54:25,414 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_rsyslog'>)
2024-02-09 20:54:25,414 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2024-02-09 20:54:25,414 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2024-02-09 20:54:25,415 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2024-02-09 20:54:25,415 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2024-02-09 20:54:25,415 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_selinux - wb: [644] 25 bytes
2024-02-09 20:54:25,416 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_selinux (recursive=False)
2024-02-09 20:54:25,418 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_selinux (recursive=False)
2024-02-09 20:54:25,419 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_selinux'>)
2024-02-09 20:54:25,433 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2024-02-09 20:54:25,433 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2024-02-09 20:54:25,433 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2024-02-09 20:54:25,433 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2024-02-09 20:54:25,433 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2024-02-09 20:54:25,434 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2024-02-09 20:54:25,434 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2024-02-09 20:54:25,435 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2024-02-09 20:54:25,435 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_users_groups - wb: [644] 25 bytes
2024-02-09 20:54:25,436 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_users_groups (recursive=False)
2024-02-09 20:54:25,438 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_users_groups (recursive=False)
2024-02-09 20:54:25,449 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_users_groups'>)
2024-02-09 20:54:25,450 - __init__.py[INFO]: User ec2-user already exists, skipping.
2024-02-09 20:54:25,450 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2024-02-09 20:54:25,540 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2024-02-09 20:54:25,541 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2024-02-09 20:54:25,542 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2024-02-09 20:54:25,543 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2024-02-09 20:54:25,549 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2024-02-09 20:54:25,550 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2024-02-09 20:54:25,550 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2024-02-09 20:54:25,551 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2024-02-09 20:54:25,551 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_ssh - wb: [644] 25 bytes
2024-02-09 20:54:25,552 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_ssh (recursive=False)
2024-02-09 20:54:25,554 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_ssh (recursive=False)
2024-02-09 20:54:25,554 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_ssh'>)
2024-02-09 20:54:25,555 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2024-02-09 20:54:25,581 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2024-02-09 20:54:25,612 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2024-02-09 20:54:25,633 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2024-02-09 20:54:25,651 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2024-02-09 20:54:25,652 - util.py[DEBUG]: Read 130 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2024-02-09 20:54:25,652 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2024-02-09 20:54:25,652 - util.py[DEBUG]: Read 210 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2024-02-09 20:54:25,652 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-02-09 20:54:25,653 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-02-09 20:54:25,655 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
2024-02-09 20:54:25,656 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=False)
2024-02-09 20:54:25,656 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2024-02-09 20:54:25,656 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-02-09 20:54:25,657 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-02-09 20:54:25,657 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2024-02-09 20:54:25,657 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2024-02-09 20:54:25,657 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2024-02-09 20:54:25,657 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2024-02-09 20:54:25,657 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-02-09 20:54:25,658 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-02-09 20:54:25,658 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2024-02-09 20:54:25,669 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-02-09 20:54:25,669 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-02-09 20:54:25,670 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2024-02-09 20:54:25,672 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2024-02-09 20:54:25,673 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-02-09 20:54:25,673 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-02-09 20:54:25,673 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2024-02-09 20:54:25,673 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2024-02-09 20:54:25,673 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2024-02-09 20:54:25,674 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2024-02-09 20:54:25,674 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-02-09 20:54:25,674 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-02-09 20:54:25,674 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2024-02-09 20:54:25,676 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2024-02-09 20:54:25,676 - main.py[DEBUG]: Ran 17 modules with 0 failures
2024-02-09 20:54:25,677 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp8n4pd9r9) - w: [644] 486 bytes/chars
2024-02-09 20:54:25,677 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-02-09 20:54:25,677 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2024-02-09 20:54:25,677 - util.py[DEBUG]: cloud-init mode 'init' took 2.334 seconds (2.33)
2024-02-09 20:54:25,677 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2024-02-09 20:54:26,791 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Fri, 09 Feb 2024 20:54:26 +0000. Up 11.30 seconds.
2024-02-09 20:54:26,799 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:26,800 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:26,809 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:26,809 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:26,819 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:26,820 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:26,822 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:26,823 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:26,829 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:26,830 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:26,839 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:26,840 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:26,843 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:26,843 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:26,859 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:26,859 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:26,862 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:26,862 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:26,869 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:26,869 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:26,872 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-02-09 20:54:26,872 - modules.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
2024-02-09 20:54:26,873 - modules.py[DEBUG]: Running module keyboard (<module 'cloudinit.config.cc_keyboard' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keyboard.py'>) with frequency once-per-instance
2024-02-09 20:54:26,873 - handlers.py[DEBUG]: start: modules-config/config-keyboard: running config-keyboard with frequency once-per-instance
2024-02-09 20:54:26,873 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_keyboard - wb: [644] 25 bytes
2024-02-09 20:54:26,876 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_keyboard (recursive=False)
2024-02-09 20:54:26,890 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_keyboard (recursive=False)
2024-02-09 20:54:26,890 - helpers.py[DEBUG]: Running config-keyboard using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_keyboard'>)
2024-02-09 20:54:26,890 - cc_keyboard.py[DEBUG]: Skipping module named keyboard, no 'keyboard' section found
2024-02-09 20:54:26,891 - handlers.py[DEBUG]: finish: modules-config/config-keyboard: SUCCESS: config-keyboard ran successfully
2024-02-09 20:54:26,891 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2024-02-09 20:54:26,891 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2024-02-09 20:54:26,891 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_locale - wb: [644] 24 bytes
2024-02-09 20:54:26,892 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_locale (recursive=False)
2024-02-09 20:54:26,893 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_locale (recursive=False)
2024-02-09 20:54:26,894 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_locale'>)
2024-02-09 20:54:26,894 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2024-02-09 20:54:26,894 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2024-02-09 20:54:26,894 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2024-02-09 20:54:26,894 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2024-02-09 20:54:26,895 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2024-02-09 20:54:26,895 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 17 bytes
2024-02-09 20:54:26,898 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2024-02-09 20:54:26,901 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2024-02-09 20:54:26,902 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2024-02-09 20:54:26,902 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2024-02-09 20:54:26,902 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2024-02-09 20:54:26,902 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_set_passwords - wb: [644] 25 bytes
2024-02-09 20:54:26,903 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_set_passwords (recursive=False)
2024-02-09 20:54:26,904 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_set_passwords (recursive=False)
2024-02-09 20:54:26,905 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_set_passwords'>)
2024-02-09 20:54:26,905 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2024-02-09 20:54:26,939 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-02-09 20:54:26,940 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-02-09 20:54:26,940 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2024-02-09 20:54:26,940 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2024-02-09 20:54:26,940 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2024-02-09 20:54:26,941 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2024-02-09 20:54:26,941 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2024-02-09 20:54:26,941 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_yum_variables - wb: [644] 24 bytes
2024-02-09 20:54:26,942 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_yum_variables (recursive=False)
2024-02-09 20:54:26,944 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_yum_variables (recursive=False)
2024-02-09 20:54:26,945 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_yum_variables'>)
2024-02-09 20:54:26,945 - cc_yum_variables.py[INFO]: handling yum-variables
2024-02-09 20:54:26,945 - cc_yum_variables.py[INFO]: cfg = {'cloud_final_modules': [['scripts-user', 'always']], 'repo_releasever': 2023.3, 'repo_upgrade': 'none', 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2024-02-09 20:54:26,945 - cc_yum_variables.py[INFO]: No yum vars to delete
2024-02-09 20:54:26,945 - cc_yum_variables.py[INFO]: No yum vars to set
2024-02-09 20:54:26,945 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2024-02-09 20:54:26,945 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2024-02-09 20:54:26,945 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2024-02-09 20:54:26,945 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_yum_add_repo - wb: [644] 25 bytes
2024-02-09 20:54:26,946 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_yum_add_repo (recursive=False)
2024-02-09 20:54:26,947 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_yum_add_repo (recursive=False)
2024-02-09 20:54:26,948 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_yum_add_repo'>)
2024-02-09 20:54:26,948 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2024-02-09 20:54:26,948 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2024-02-09 20:54:26,948 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2024-02-09 20:54:26,949 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2024-02-09 20:54:26,959 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_ntp - wb: [644] 25 bytes
2024-02-09 20:54:26,960 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_ntp (recursive=False)
2024-02-09 20:54:26,961 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_ntp (recursive=False)
2024-02-09 20:54:26,962 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_ntp'>)
2024-02-09 20:54:26,962 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2024-02-09 20:54:26,962 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2024-02-09 20:54:26,962 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2024-02-09 20:54:26,963 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2024-02-09 20:54:26,963 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_timezone - wb: [644] 25 bytes
2024-02-09 20:54:26,964 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_timezone (recursive=False)
2024-02-09 20:54:26,965 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_timezone (recursive=False)
2024-02-09 20:54:26,965 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_timezone'>)
2024-02-09 20:54:26,965 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2024-02-09 20:54:26,966 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2024-02-09 20:54:26,966 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2024-02-09 20:54:26,966 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2024-02-09 20:54:26,966 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f3c7ee29340>)
2024-02-09 20:54:26,966 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2024-02-09 20:54:26,966 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2024-02-09 20:54:26,966 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2024-02-09 20:54:26,966 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2024-02-09 20:54:26,967 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_runcmd - wb: [644] 25 bytes
2024-02-09 20:54:26,967 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_runcmd (recursive=False)
2024-02-09 20:54:26,969 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_runcmd (recursive=False)
2024-02-09 20:54:26,979 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-04a2fb82429909c7b/sem/config_runcmd'>)
2024-02-09 20:54:26,980 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2024-02-09 20:54:26,980 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2024-02-09 20:54:26,980 - main.py[DEBUG]: Ran 9 modules with 0 failures
2024-02-09 20:54:26,980 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpqsu3ot3t) - w: [644] 512 bytes/chars
2024-02-09 20:54:26,981 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-02-09 20:54:26,981 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2024-02-09 20:54:26,981 - util.py[DEBUG]: cloud-init mode 'modules' took 0.398 seconds (0.40)
2024-02-09 20:54:26,981 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2024-02-09 20:54:27,975 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Fri, 09 Feb 2024 20:54:27 +0000. Up 12.50 seconds.
2024-02-09 20:54:27,976 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-02-09 20:54:27,977 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-02-09 20:54:27,979 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-02-09 20:54:27,980 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency always
2024-02-09 20:54:27,981 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency always
2024-02-09 20:54:27,981 - helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7f0b9cb41e20>)
2024-02-09 20:54:27,981 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=False, capture=False)
